apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-app
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
      - name: currency-app
        image: urchymanny/currency-converter:v3
        envFrom:
        - secretRef:
            name: app-secret
        - configMapRef:
            name: app-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /rails/storage
          name: currency-app-pv
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: currency-app-pv
        persistentVolumeClaim:
          claimName: currency-app-pvc
