apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: currency-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 # or "gp3", depending on your EKS setup
