apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-pg
  template:
    metadata:
      labels:
        app: currency-pg
    spec:
      containers:
      - name: currency-pg
        image: postgres:14.2-alpine
        envFrom:
        - secretRef:
            name: my-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: currency-pg-pv
          mountPath: /var/lib/postgresql/data
          subPath: data
      volumes:
      - name: currency-pg-pv
        persistentVolumeClaim:
          claimName: currency-pg-pvc

