apiVersion: v1
kind: PersistentVolume
metadata:
  name: currency-pg-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /var/lib/postgresql/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: currency-pg-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  volumeName: currency-pg-pv
  storageClassName: standard

