apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: MY_SUPER_SECRET
  FCA_KEY: fca_live_4oq9xKkfwunWfGZXKzdYQVZjeOpaJacV4gtmFs9L
  POSTGRES_USER: uchenna
  POSTGRES_PASSWORD: UCHENNA-PASSWORD
  RAILS_MASTER_KEY: e5e0b65a061f1e4a9392c3c7ee478280
